### ISSUE TITLE
Ansible extension fails to lint playbooks in online editor

### ISSUE THREAD

**Issue by craig-br** [ansible-security/workshop-examples#6]
#### Summary
- When editing a playbook, an error message at the bottom right of the online editor UI appears:

```
Command failed: ansible-lint  --offline --nocolor -f codeclimate /home/student1/enrich_log_sources.yml /bin/sh: ansible-lint: command not found
```
![image](https://user-images.githubusercontent.com/42829306/136837495-6dba9ac6-b233-48a1-bf8d-2f0f6e2804ae.png)

**Comment by eelson2** [comment]
did you resolve this error you found?  I am running into the same error and scratching my head as to what will resolve it.
